export const messages = [
{ id: 1, content: 'Hola Lucas' },
{ id: 2, content: 'Hola Yamila' },
{ id: 3, content: 'Como andas?' },
{ id: 4, content: 'Muy bien, y vos?' },
{ id: 5, content: 'Excelente' },
{ id: 6, content: 'Genial! Salimos?' },
{ id: 7, content: 'Hola Lucas' },
{ id: 8, content: 'Hola Yamila' },
{ id: 9, content: 'Como andas?' },
{ id: 10, content: 'Muy bien, y vos?' },
{ id: 11, content: 'Excelente' },
{ id: 12, content: 'Genial! Salimos?' },
{ id: 13, content: 'Hola Lucas' },
{ id: 14, content: 'Hola Yamila' },
{ id: 15, content: 'Como andas?' },
/*{ id: 16, content: 'Muy bien, y vos?' },
{ id: 17, content: 'Excelente' },
{ id: 18, content: 'Genial! Salimos?' },
{ id: 19, content: 'Hola Lucas' },
{ id: 20, content: 'Hola Yamila' },
{ id: 21, content: 'Como andas?' },
{ id: 22, content: 'Muy bien, y vos?' },
{ id: 23, content: 'Excelente' },
{ id: 24, content: 'Genial! Salimos?' },
{ id: 25, content: 'Hola Lucas' },
{ id: 26, content: 'Hola Yamila' },
{ id: 27, content: 'Como andas?' },
{ id: 28, content: 'Muy bien, y vos?' },
{ id: 29, content: 'Excelente' },
{ id: 30, content: 'Genial! Salimos?' }*/
]